---

- set_fact:
    ssh_svc: sshd

- name: Alpine | Extra packages install
  apk: name={{item}} state=present update_cache=yes
  with_items:
    - git
    - gnupg
    - rng-tools@testing
    - acct
    - sysstat
    - arpwatch
    - logcheck
#    - aide
#    - rkhunter
#    - lynis
