---

- set_fact:
    ssh_svc: sshd

- name: Alpine | Extra packages install
  apk: name={{item}} state=present update_cache=yes
  with_items:
    - git
    - gnupg
    - rng-tools@testing
    - acct
    - sysstat
    - arpwatch
    - logcheck
#    - aide
#    - rkhunter
#    - lynis

- name: Alpine | upgrade all packages to the latest version
  apk: upgrade=yes
  async: 3600
  poll: 300
  register: distout
  when: (harden_upgradeall is defined and harden_upgradeall) and (travisci is not defined or not travisci)

