---

- name: Ensure logrotate package is present
  package:
    name: logrotate
    state: present

- name: review logrotate configuration
  replace:
    dest: /etc/logrotate.conf
    regexp: "{{ item.re }}"
    replace: "{{ item.rep }}"
    backup: yes
  with_items:
    - { re: '^(weekly|daily|monthly)', rep: 'daily' }
    - { re: '^rotate .*', rep: "rotate {{ harden_logrotate_days|int }}" }
