---
- set_fact:
    daemons: >
      {%- set list = [ 'sshd', 'rsyslog' ] %}
      {%- if monit_osqueryd %}
      {%-   set list = list.append('osqueryd') %}
      {%- endif %}
      {%- if monit_auditd %}
      {%-   set list = list.append('auditd') %}
      {%- endif %}
      {{- list -}}

- block:
    - name: apt | monit package
      apt: name={{item}} state=present
      with_items:
        - monit
    - name: set monit configurations
      template: "src={{ item }}-monit.j2 dest={{ monit_confdir }}/{{ item }} mode=0644 backup=yes"
      with_items: "{{ daemons }}"
      notify:
        - restart monit
    - block:
        - name: Trusty+Jessie | enable monit
          file: "src={{ monit_confdir }}/{{ item }} dest=/etc/monit/conf.d/{{ item }} state=link"
          with_items: "{{ daemons }}"
          notify:
            - restart monit
      when: ansible_distribution_release == 'trusty' or ansible_distribution_release == 'jessie'
    - block:
        - name: Xenial | enable monit
          file: "src={{ monit_confdir }}/{{ item }} dest=/etc/monit/conf-enabled/{{ item }} state=link"
          with_items: "{{ daemons }}"
          notify:
            - restart monit
      when: ansible_distribution_release == 'xenial'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- block:
    - name: yum | monit package
      yum: name={{item}} state=present
      with_items:
        - monit
    - name: set monit configurations
      template: "src={{ item }}-monit.j2 dest={{ monit_confdir }}/{{ item }} mode=0644 backup=yes"
      with_items: "{{ daemons }}"
      notify:
        - restart monit
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: allow monit status/summary from localhost
  replace: dest={{ monitrc }} regexp={{ item.re }} replace={{ item.rep }}
  with_items:
    - { re: '^# set httpd port 2812 and', rep: ' set httpd port 2812 and' }
    - { re: '^#    \s*use address localhost', rep: '     use address localhost' }
    - { re: '^#    \s*allow localhost', rep: '     allow localhost' }
#    - { re: '^#     allow admin:monit', rep: '     allow admin:monit' }

- name: ensure monit service is enabled and started
  service: name=monit state=started enabled=yes

- meta: flush_handlers
- include: "monit-checkmonitor.yml daemon={{ item }}"
  with_items: "{{ daemons }}"
