---
## https://jerrygamblin.com/2017/08/24/disallow-million-most-common-passwords/
## http://thegarywilson.com/blog/2006/using-cracklib-to-require-stronger-passwords/

- name: recover dictionary files
  get_url:
    url: "{{ item.u }}"
    dest: "/usr/share/dict/{{ item.u | basename }}"
    mode: '0644'
    checksum: "{{ item.h }}"
  with_items: "{{ harden_cracklib_dict }}"
  when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'

- name: check for cracklib refresh marker
  stat:
    path: /usr/share/dict/.ansible_cracklib_update
  register: cracklibrefresh
- block:
    - name: Debian | create cracklib database
      command: "create-cracklib-dict /usr/share/dict/*"
## just a refresh = not idempotent
#      args:
#        creates: /var/cache/cracklib/cracklib_dict.pwd
  when: ansible_os_family == 'Debian' and not cracklibrefresh.stat.exists
- block:
    - name: RedHat | create cracklib database
      shell: "mkdict /usr/share/dict/* | packer /usr/lib/cracklib_dict"
#      args:
#        creates: /usr/lib/cracklib_dict.pwd
  when: ansible_os_family == 'RedHat' and not cracklibrefresh.stat.exists
- name: add cracklib refresh marker
  file:
    path: /usr/share/dict/.ansible_cracklib_update
    state: touch
  when: not cracklibrefresh.stat.exists
