---

- name: Redhat| Remove some packages
  yum: name={{item}} state=absent
  with_items:
    - rpcbind
  when: harden_use_rpc is not defined or not harden_use_rpc

## https://help.ubuntu.com/lts/serverguide/automatic-updates.html
## FIXME! slow... even when rerun
#- name: yum | upgrade all packages to the latest version
#  yum: name=* state=latest
#  async: 3600
#  poll: 300
#  register: distout
#  when: travisci is not defined or not travisci
#- debug: var=distout.stdout_lines

- name: set better login.defs - redhat only
  lineinfile: "dest=/etc/login.defs regexp={{ item.r }} line={{ item.l }}"
  with_items:
    - { r: '^PASS_MIN_LEN', l: 'PASS_MIN_LEN    10' }

- name: password set for single mode
  lineinfile: dest=/etc/sysconfig/init regexp='^SINGLE=' line='SINGLE=/sbin/sulogin'

- name: Redhat | Ensure services are running and enabled on boot.
  service: name={{ item }} state=started enabled=yes
  with_items:
    - psacct
    - haveged
    - auditd
    - arpwatch
#    - yum-cron

## https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Security_Guide/chap-system_auditing.html
- name: configure audit system
  template: src=audit.rules.j2 dest=/etc/audit/rules.d/audit.rules mode=0644 backup=yes
  notify:
    - restart auditd
  tags: auditd

