---

- name: Redhat| Remove some packages
  yum: name={{item}} state=absent
  with_items:
    - rpcbind
  when: harden_use_rpc is not defined or not harden_use_rpc

## https://help.ubuntu.com/lts/serverguide/automatic-updates.html
## FIXME! slow... even when rerun
- block:
    - name: yum | upgrade all packages to the latest version
      yum: name=* state=latest
      async: 3600
      poll: 300
      register: distout
    - debug: var=distout.stdout_lines
  when: (harden_upgradeall is defined and harden_upgradeall) and (travisci is not defined or not travisci)

- name: set better login.defs - redhat only
  lineinfile: "dest=/etc/login.defs regexp={{ item.r }} line={{ item.l }}"
  with_items:
    - { r: '^PASS_MIN_LEN', l: 'PASS_MIN_LEN    10' }

- name: Ensure initscripts package is present
  package:
    name: initscripts
    state: present

- name: password set for single mode
  lineinfile: dest=/etc/sysconfig/init regexp='^SINGLE=' line='SINGLE=/sbin/sulogin'

- debug: var=ansible_virtualization_type
- set_fact:
    harden_services_containers: []
  when: (ansible_virtualization_type is defined and (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker"))
- name: Redhat | Ensure services are running and enabled on boot.
  service: name={{ item }} state=started enabled=yes
  with_items:
    - "{{ harden_services }}"
    - "{{ harden_services_containers }}"

- name: initialize rootkithunter db
  command: "rkhunter --propupd creates=/var/lib/rkhunter/db/rkhunter.dat"

- include: selinux.yml
  when: not (ansible_virtualization_type is defined and (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker"))

- include: yum-cron.yml
  when: harden_security_update_auto

