---

- name: Configure sudo password timeout
  lineinfile:
    dest: /etc/sudoers
    regexp: "^Defaults        .*"
    line: "Defaults        env_reset,timestamp_timeout={{ harden_sudo_timeout | default(15) }}"
    backup: yes
    validate: 'visudo -cf %s'
