---

- include: sshd.yml
  when: harden_sshd_review

## Bash history to syslog (since 4.1) but need re-compile for most distributions
## https://isc.sans.edu/forums/diary/Improving+Bash+Forensics+Capabilities/20887/
## https://blog.rootshell.be/2009/02/28/bash-history-to-syslog/
## http://blog.hellosa.org/2013/07/27/log-bash-history-to-syslog-on-centos-6.html
## http://binbash.fr/2012/09/05/bash-syslog/

- stat: path=/var/log/account/pacct
  register: pacct
## FIXME! might be not active if enabled/disabled...
- name: enable accounting
  command: "accton on creates=/var/log/account/pacct"
  environment:
    PATH: "/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"
  when: not pacct.stat.exists
## FIXME! not working on centos-6
  ignore_errors: true

- include: unix-fstab.yml
  when: harden_unix_fstab_flags is defined and harden_unix_fstab_flags and harden_mount_options != []

- name: Enforce shell timeout
  blockinfile:
    dest: /etc/profile
    marker: "### {mark} ANSIBLE MANAGED BLOCK: shell timeout ###"
    content: |
      #readonly TMOUT={{ harden_shell_timeout }}
  tags: bash

- name: configure motd
  template: src=motd.j2 dest={{ item }} mode=0644 backup=yes
  with_items:
    - /etc/motd
    - /etc/issue.net

