---

## https://groups.google.com/forum/#!msg/ansible-project/7MhOICPWkaI/rADYaeaRDlsJ
- name: Secure Mount options
  mount: name={{ item.mount }} src={{ item.device }} state=present fstype={{ item.fstype }} opts={{ harden_mount_options[item.mount] | default(item.options) }}
  with_items: "{{ ansible_mounts }}"
## Note: better to use notify than state=mounted which is immediate. other part of role might conflict else
  notify:
    - reload fstab

