---

- name: restart sshd
  service: name={{ ssh_svc }} state=restarted

- name: restart iptables
  service: name=iptables-persistent state=restarted
  when: ansible_distribution == 'Debian' or (ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int < 16)

- name: restart iptables - xenial
  service: name=netfilter-persistent state=restarted
  when: (ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int >= 16)

- name: restart auditd
  service: name=auditd state=restarted
  when: not (ansible_virtualization_type is defined and (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker")) and not (ansible_os_family == "RedHat" and ansible_distribution_version.split('.')[0] == '7')

## https://groups.google.com/forum/#!topic/ansible-project/pv1h1Ne7nSk
## https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Security_Guide/sec-starting_the_audit_service.html
- name: restart auditd - rhel7
  command: "service auditd restart"
  when: not (ansible_virtualization_type is defined and (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker")) and (ansible_os_family == "RedHat" and ansible_distribution_version.split('.')[0] == '7')

## FIXME! on centos7, it seems we lose some path when remounting all (cgroup, mqueue, hugetlbfs...) and cant ssh after... vagrant reload: fine?
- name: reload fstab
  shell: "umount -a; mount -a"
#  shell: "mount > /root/mount1; umount -a; mount -a; mount > /root/mount2; diff -urN /root/mount[12]"
  ignore_errors: true
  when: ansible_os_family != 'RedHat'

- name: restart sysstat
  service: name=sysstat state=restarted

- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: restart fail2ban
  service: name=fail2ban state=restarted

- name: restart osquery
  service: name=osqueryd state=restarted

- name: restart journald
  service: name=systemd-journald state=restarted

- name: reload udev
  command: "udevadm control --reload-rules"

- name: restart monit
  service: name=monit state=restarted
  when: not (ansible_virtualization_type is defined and ansible_virtualization_type == "docker")
